---
- name: Update pkg cache.
  command: pkg update -f
  environment:
    ASSUME_ALWAYS_YES: "yes"
  tags: ['skip_ansible_lint']

- name: Ensure nginx is installed.
  pkgng:
    name: "{{ nginx_package_name }}"
    state: present

- name: Add directory for snippets
  file:
    state: directory
    path: /usr/local/etc/nginx/snippets
    owner: root
    group: "{{ root_group }}"
    mode: 0755

- name: Create logs directory.
  file:
    path: /var/log/nginx
    state: directory
